# Generated by Django 3.1.3 on 2020-11-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccines',
            new_name='Vaccine',
        ),
    ]
